### ISSUE TITLE
semver's like `1.0` or `1` are not valid and can not be sorted

### ISSUE THREAD

**Issue by leroy0211** [ragingwind/semver-sort#6]
When I want to sort an array of semvers like the ones below, it can not sort them, because they don't match the full semver specification

```js
var versions = [
   '1.16.0',
   '1.16.3'
   '1.16',
   '1.15',
   '2'
]
```

**Comment by ragingwind** [comment]
What results did you expect? it supports sorting of semver not invalid semver.

**Comment by leroy0211** [comment]
I've took a look at the semver standard, and you are right. It's not officially semver. 

But my use case is as follows. We want to sort all the available docker tags, which can be either fully semver `X.Y.Z` but also only the major or minor version `X.Y` or `X`. Each of the non-official semvers will match the latest official semver for that version. Like. `7.3.6`(which is the latest 7.3) and `7.3` and `7` are all the same. Just like the docker officials. So I wanted to sort all those official and non-official versions.

But I think I need to do some sorting of my own for this usecase then. Thanks anyways.
